"""Pack&Go 兼容的系统级文件包生成器。

仅生成单个 .mod 不足以让 IRC5P 控制器直接加载并运行。完整可加载包至少需要：
  - <ModuleName>.mod  : 主程序模块（已有）
  - BASE.sys          : 系统模块，含 Home 位 / 错误恢复 trap
  - <Task>.pgf        : 程序文件列表，控制器据此加载模块到 T_ROB1
  - README.md         : 三种加载方式的说明（RobotStudio / FlexPendant / USB）

本模块输出这四件，让用户能直接把目录拷到控制器 HOME 文件夹或通过 RobotStudio
Pack&Go 还原。
"""
from __future__ import annotations

from pathlib import Path
from typing import Literal

from abb_agent.rapid.module_template import extract_module_name

ControllerKind = Literal["IRC5", "IRC5P"]


def _extension_for(name: str) -> str:
    """系统模块用 .sys，其余用 .mod。"""
    return ".sys" if name.upper() == "BASE" else ".mod"


def build_pgf(module_names: list[str]) -> str:
    """生成 .pgf XML 文件，列出 T_ROB1 任务要加载的所有模块。

    ABB 控制器读取 .pgf 时按顺序加载文件。系统模块（.sys）通常排在最前。
    encoding 声明 ISO-8859-1；写盘时一致使用 latin-1 + CRLF。
    """
    lines = [
        '<?xml version="1.0" encoding="ISO-8859-1" ?>',
        "<Program>",
    ]
    for name in module_names:
        ext = _extension_for(name)
        lines.append(f"    <Module>{name}{ext}</Module>")
    lines.append("</Program>")
    return "\n".join(lines) + "\n"


def build_sys_module(*, controller: ControllerKind = "IRC5") -> str:
    """生成 BASE.sys 系统模块。

    包含：
      - 标准 Home 位 robtarget（pHome）
      - 全局错误处理 trap (errhandler)
      - 复位例程 PROC reset_to_home() 用于异常后回安全位

    SYSMODULE 属性确保模块在 PP-to-main 时仍保留。

    注意：本模块输出**全 ASCII**，因为 RobotWare 老版本加载 .sys 时默认按
    ISO-8859-1 解码，非 ASCII 字符（中文注释）会导致加载失败。生成的中文
    解释请放到与 .sys 同目录的 README.md 而不是 .sys 内部。
    """
    body_recovery_comment = (
        "        ! IRC5P recovery: brushdata handles gun timing automatically;\n"
        "        ! reset auxiliary fan/atom signals here, then call reset_to_home\n"
        if controller == "IRC5P"
        else "        ! Recovery: shut spray, then call reset_to_home\n"
    )

    extra_io_resets = (
        "        Reset doFanOn;\n"
        "        Reset doAtomOn;\n"
        if controller == "IRC5P"
        else "        Reset doSprayOn;\n"
    )

    return (
        "MODULE BASE (SYSMODULE)\n"
        f"    ! Generated by abb-agent -- controller={controller}\n"
        "    ! NOTE: this file must remain pure ASCII to load on RobotWare\n"
        "    !       that defaults to ISO-8859-1 decoding.\n"
        "\n"
        "    ! ---------------- Home position ----------------\n"
        "    ! Safe Home pose. Field engineer MUST re-teach this on-site;\n"
        "    ! below is placeholder only.\n"
        "    PERS robtarget pHome := "
        "[[0,0,500],[1,0,0,0],[0,0,0,0],[9E9,9E9,9E9,9E9,9E9,9E9]];\n"
        "\n"
        "    ! ---------------- Error trap ----------------\n"
        "    VAR intnum iErrHandler;\n"
        "\n"
        "    TRAP errhandler\n"
        f"{body_recovery_comment}"
        f"{extra_io_resets}"
        "        ! Do NOT MoveJ/MoveL inside the trap; defer motion to reset_to_home.\n"
        "    ENDTRAP\n"
        "\n"
        "    ! ---------------- Recovery routine ----------------\n"
        "    PROC reset_to_home()\n"
        "        ! Call after exception handling to return robot to Home.\n"
        "        ConfL\\Off;\n"
        "        SingArea\\Wrist;\n"
        "        MoveJ pHome, v500, fine, tool0;\n"
        "    ENDPROC\n"
        "\n"
        "    ! ---------------- System init ----------------\n"
        "    PROC sys_init()\n"
        "        ! Called on power-on / PP-to-main.\n"
        "        ! TODO: bind error trap to a real EIO signal that exists in\n"
        "        ! your controller's EIO.cfg, e.g.:\n"
        "        !     CONNECT iErrHandler WITH errhandler;\n"
        "        !     ISignalDI \\Single, diEmergencyStop, 1, iErrHandler;\n"
        "        ! Left commented out so this module compiles on a fresh\n"
        "        ! controller without diEmergencyStop defined.\n"
        "    ENDPROC\n"
        "\n"
        "ENDMODULE\n"
    )


def build_load_readme(
    *, module_filename: str, controller: ControllerKind = "IRC5"
) -> str:
    """生成加载到 IRC5/IRC5P 控制器的说明 README。"""
    paint_note = (
        "\n> **[警告]** 控制器必须已安装 RobotWare **Paint 选项 (687-1 PaintWare)**，"
        "否则 PaintL/PaintC 指令会报「未知指令」。\n"
        if controller == "IRC5P"
        else ""
    )

    return (
        f"# 加载到 {controller} 控制器的三种方式\n"
        f"{paint_note}\n"
        f"本目录包含以下文件，需要全部传到控制器：\n"
        f"- `{module_filename}` — 主程序模块\n"
        f"- `BASE.sys` — 系统模块（Home 位 + 错误处理）\n"
        f"- `T_ROB1.pgf` — 任务程序清单，控制器据此加载模块\n"
        f"\n"
        f"---\n"
        f"\n"
        f"## 方式 1：RobotStudio（推荐）\n"
        f"1. RobotStudio → File → New → Solution with Empty Station\n"
        f"2. Add Controller → Virtual Controller → 选含 {controller} "
        f"对应 RobotWare 的系统\n"
        f"3. 把整个本目录拖入 Controller → T_ROB1 → Modules\n"
        f"4. 右键 `T_ROB1` → Load Program → 选 `T_ROB1.pgf`\n"
        f"5. 验证编译通过后，**Pack & Go**：File → Pack & Go → 选目标文件夹\n"
        f"6. 把生成的 `.rspag` 文件拷到 U 盘，在真实控制器 FlexPendant → "
        f"Backup and Restore → Restore from .rspag\n"
        f"\n"
        f"## 方式 2：FlexPendant 直接加载\n"
        f"1. 把本目录拷到 U 盘根目录\n"
        f"2. 控制器插入 U 盘\n"
        f"3. FlexPendant → Program Editor → File → Open → 选 USB:/T_ROB1.pgf\n"
        f"4. 提示「替换当前程序」时确认\n"
        f"\n"
        f"## 方式 3：FTP / 网络共享\n"
        f"1. 控制器 IP 通常是 192.168.125.1（默认）\n"
        f"2. `ftp 192.168.125.1` 登入（用户 / 密码见控制器铭牌）\n"
        f"3. `cd /HOME` → `put {module_filename}` → `put BASE.sys` → `put T_ROB1.pgf`\n"
        f"4. 在 FlexPendant 上 Reload\n"
        f"\n"
        f"---\n"
        f"\n"
        f"## 上线前必做的 4 件事\n"
        f"1. **TCP 标定**：用 4 点法重新标定 `tSprayGun`，把结果填到 `{module_filename}` 顶部\n"
        f"2. **工件坐标系**：把 `wobjPart` 改成实际工件位姿\n"
        f"3. **IO 名称对齐**：用 RobotStudio 打开 EIO.cfg，把代码中的 `doSprayOn` 等改成实际信号名\n"
        f"4. **手动 T1 慢速验证**：示教器切手动模式 250mm/s，单步执行 main()，目视确认每点不撞机\n"
    )


def _write_latin1_crlf(path: Path, text: str) -> None:
    """ABB 控制器友好的写法：ISO-8859-1 编码 + CRLF 行终止符。

    非 Latin-1 字符替换为 '?'（写入前不该有，但作为兜底；调用方应保证 ASCII）。
    """
    crlf = text.replace("\r\n", "\n").replace("\n", "\r\n")
    path.write_bytes(crlf.encode("iso-8859-1", errors="replace"))


def bundle_for_controller(
    out_dir: Path,
    module_code: str,
    *,
    controller: ControllerKind = "IRC5",
    force: bool = False,
) -> dict[str, Path]:
    """把单个模块代码扩展成完整可加载目录。

    - .pgf 与 .sys 用 ISO-8859-1 + CRLF 写入（ABB 控制器要求）
    - .mod 用 UTF-8 写入（保留 LLM 可能输出的中文注释，新一代 RobotWare 支持）
    - README.md 用 UTF-8（开发者读，不上控制器）

    Args:
        out_dir: 输出目录
        module_code: 主模块 RAPID 代码
        controller: 目标控制器类型
        force: True 时覆盖已存在的 BASE.sys / T_ROB1.pgf；默认 False 拒绝覆盖

    Returns:
        dict 键是文件角色（module/pgf/sys/readme），值是落盘 Path。
        多出一个 'manifest' 键指向 MANIFEST.ok（写完成功标志）。

    Raises:
        FileExistsError: out_dir 已存在 BASE.sys/T_ROB1.pgf 且 force=False
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    module_name = extract_module_name(module_code)
    module_filename = f"{module_name}.mod"

    module_path = out_dir / module_filename
    sys_path = out_dir / "BASE.sys"
    pgf_path = out_dir / "T_ROB1.pgf"
    readme_path = out_dir / "README.md"
    manifest_path = out_dir / "MANIFEST.ok"

    # 防覆盖检查
    if not force:
        existing = [p for p in (sys_path, pgf_path, module_path) if p.exists()]
        if existing:
            names = ", ".join(p.name for p in existing)
            raise FileExistsError(
                f"目标目录 {out_dir} 已存在 {names}；用 force=True 覆盖。"
            )

    # 删除旧 MANIFEST.ok（写完后再生成 → 半写状态可见）
    if manifest_path.exists():
        manifest_path.unlink()

    module_path.write_text(module_code, encoding="utf-8")
    _write_latin1_crlf(sys_path, build_sys_module(controller=controller))
    _write_latin1_crlf(pgf_path, build_pgf(["BASE", module_name]))
    readme_path.write_text(
        build_load_readme(module_filename=module_filename, controller=controller),
        encoding="utf-8",
    )

    # 全部写完才创建标志，让外部能区分「完整」vs「半写」
    manifest_path.write_text(
        f"bundle complete\ncontroller={controller}\nmodule={module_filename}\n",
        encoding="utf-8",
    )

    return {
        "module": module_path,
        "sys": sys_path,
        "pgf": pgf_path,
        "readme": readme_path,
        "manifest": manifest_path,
    }
